---
hero_image: images/banner.png
theme: violet
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Archery
description: Shoot arrows as close to the bullseye as you can.
original_url: https://codeclubprojects.org/en-GB/scratch/archery
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: Aiming arrows
- title: Shooting arrows
- title: 'Challenge: Different scores'